Running on node: gnode02
Using 4 CPU cores
CUDA devices available:
Sun Jul 13 16:27:52 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe           On | 00000000:65:00.0 Off |                    0 |
| N/A   30C    P0               42W / 300W|      0MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
/home/3157425/.conda/envs/rlworlds310/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 2.2.6
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/home/3157425/rl-worlds/simple-rl-worlds/src/scripts/representation_metrics/analyse_smoothness.py", line 44, in <module>
    import seaborn as sns
  File "/home/3157425/.conda/envs/rlworlds310/lib/python3.10/site-packages/seaborn/__init__.py", line 5, in <module>
    from .relational import *  # noqa: F401,F403
  File "/home/3157425/.conda/envs/rlworlds310/lib/python3.10/site-packages/seaborn/relational.py", line 21, in <module>
    from ._statistics import EstimateAggregator, WeightedAggregator
  File "/home/3157425/.conda/envs/rlworlds310/lib/python3.10/site-packages/seaborn/_statistics.py", line 32, in <module>
    from scipy.stats import gaussian_kde
  File "/home/3157425/.conda/envs/rlworlds310/lib/python3.10/site-packages/scipy/stats/__init__.py", line 453, in <module>
    from ._stats_py import *
  File "/home/3157425/.conda/envs/rlworlds310/lib/python3.10/site-packages/scipy/stats/_stats_py.py", line 38, in <module>
    from scipy.spatial.distance import cdist
  File "/home/3157425/.conda/envs/rlworlds310/lib/python3.10/site-packages/scipy/spatial/__init__.py", line 102, in <module>
    from ._kdtree import *
  File "/home/3157425/.conda/envs/rlworlds310/lib/python3.10/site-packages/scipy/spatial/_kdtree.py", line 5, in <module>
    from ._ckdtree import cKDTree, cKDTreeNode
  File "_ckdtree.pyx", line 1, in init scipy.spatial._ckdtree
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
